source/QAQC/QAQC/urls.py
from django.conf import settings
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include

urlpatterns = [
    path('', include('accounts.urls')),
    path('inspection/', include('inspection.urls')),
    path('admin/', admin.site.urls, name='admin'),
    path('', include('django.contrib.auth.urls')),
    path('objects/',include('objects.urls'))
]
urlpatterns += staticfiles_urlpatterns()

source/QAQC/inspection/urls.py
from .views import *
from django.urls import path

urlpatterns = [
    # elements
    path('elements/', element_list, name='element_list'),
    path('elements/create/', element_create, name='element_create'),
    path('elements/<int:id>/update', element_update, name='element_update'),
    path('elements/<int:id>/delete', element_delete, name='element_delete'),

    # groups
    path('elements/<int:id>/groups', group_list, name='group_list'),
    path('elements/<int:id>/groups/create', group_create, name='group_create'),
    path('groups/<int:id>/update', group_update, name='group_update'),
    path('groups/<int:id>/delete', group_delete, name='group_delete'),

    # number_series
    path('number_series/', number_series_list, name='number_series_list'),
    path('number_series/create', number_series_create, name='number_series_create'),
    path('number_series/<int:id>/update', number_series_update, name='number_series_update'),
    path('number_series/<int:id>/delete', number_series_delete, name='number_series_delete'),

    # forms_type
    path('number_series/<int:id>/forms_type', form_type, name='form_type'),
    path('number_series/<int:id>/forms_type/create', form_type_create, name='form_type_create'),
    path('forms_type/<int:id>/update', form_type_update, name='form_type_update'),
    path('forms_type/<int:id>/delete', form_type_delete, name='form_type_delete'),

    # forms
    path('forms_type/<int:id>/templates', templates, name='templates'),
    path('forms_type/<int:id>/template/create', template_create, name='template_create'),
    path('template/<int:id>/update', template_update, name='template_update'),
    path('template/<int:id>/delete', template_delete, name='template_delete'),
    path('template/<int:id>/newrev', new_rev, name='new_rev'),

    # questions
    path('template/<int:id>/questions', question, name='question'),
    path('template/<int:id>/question/create', question_create, name='question_create'),
    path('template/question/<int:id>/update', question_update, name='question_update'),
    path('template/question/<int:id>/delete', question_delete, name='question_delete'),
    path('template/question/<int:id>/up', move_up, name='move_up'),
    path('template/question/<int:id>/down', move_down, name='move_down'),

    #input
    path('selectform/',select_form,name='select_form'),
    path('selectform/typecode/<int:id>', type_code, name='type_code'),
    path('selectform/typecode/inspection/<int:id>', inspection, name='inspection'),
    path('selectform/typecode/inspection/previous/<int:g>/<int:h>', previous_inspection, name='previous_inspection'),
    path('selectform2/<int:id>', select_form2, name='select_form2'),

]

source/QAQC/inspection/models.py
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField
from datetime import *


# =========DETAIL============================
class Element(models.Model):
    class Meta:
        verbose_name = 'Element'
        verbose_name_plural = 'Elements'

    element = models.CharField(max_length=50, unique=True, error_messages={
        'unique': 'Element already exist.',
    })
    description = models.CharField(max_length=200, blank=True)
    is_active = models.BooleanField(default=True)
    creation_time = models.DateTimeField(null=True, blank=True)
    creator_user_id = models.CharField(max_length=50, blank=True)
    last_modification_time = models.DateTimeField(null=True, blank=True)
    last_modifier_user_id = models.CharField(max_length=50, blank=True)
    is_deleted = models.BooleanField(default=False)
    deletion_time = models.DateTimeField(null=True, blank=True)
    delete_user_id = models.CharField(max_length=50, blank=True)

    def __str__(self):
        return str(self.element)

    pass


class Group(models.Model):
    class Meta:
        verbose_name = 'Group'
        verbose_name_plural = 'Groups'

    element_id = models.ForeignKey(Element, on_delete=models.CASCADE)
    defect_group = models.CharField(max_length=100, unique=True, error_messages={
        'unique': 'Group already exist.', })
    description = models.CharField(max_length=200, blank=True)
    is_active = models.BooleanField(default=True)
    creation_time = models.DateTimeField(null=True, blank=True)
    creator_user_id = models.CharField(max_length=50, blank=True)
    last_modification_time = models.DateTimeField(null=True, blank=True)
    last_modifier_user_id = models.CharField(max_length=50, blank=True)
    is_deleted = models.BooleanField(default=False)
    deletion_time = models.DateTimeField(null=True, blank=True)
    delete_user_id = models.CharField(max_length=50, blank=True)

    def __str__(self):
        return str(self.element_id) + ' - ' + str(self.defect_group)

    pass


# =========InspectionForm================================


class NumberSeries(models.Model):
    class Meta:
        verbose_name = 'NumberSeries'
        verbose_name_plural = 'Number_Series'

    series = models.CharField(max_length=50, unique=True, error_messages={
        'unique': 'Series name already exist.', })
    current = models.IntegerField(default=1)
    is_active = models.BooleanField(default=True)
    creation_time = models.DateTimeField(null=True, blank=True)
    creator_user_id = models.CharField(max_length=50, blank=True)
    last_modification_time = models.DateTimeField(null=True, blank=True)
    last_modifier_user_id = models.CharField(max_length=50, blank=True)
    is_deleted = models.BooleanField(default=False)
    deletion_time = models.DateTimeField(null=True, blank=True)
    delete_user_id = models.CharField(max_length=50, blank=True)

    def __str__(self):
        return str(self.series)

    pass


class FormTypeTemplate(models.Model):
    class Meta:
        verbose_name = 'FormTypeTemplate'
        verbose_name_plural = 'FormTypeTemplates'

    number_series_id = models.ForeignKey(NumberSeries, on_delete=models.CASCADE)
    form_type = models.CharField(max_length=20, unique=True, error_messages={
        'unique': 'Form type already exist.', })
    form_description = models.CharField(max_length=200, unique=True, error_messages={
        'unique': 'Short Name already exist.', })
    is_active = models.BooleanField(default=True)
    creation_time = models.DateTimeField(null=True, blank=True)
    creator_user_id = models.CharField(max_length=50, blank=True)
    last_modification_time = models.DateTimeField(null=True, blank=True)
    last_modifier_user_id = models.CharField(max_length=50, blank=True)
    is_deleted = models.BooleanField(default=False)
    deletion_time = models.DateTimeField(null=True, blank=True)
    delete_user_id = models.CharField(max_length=50, blank=True)

    def __str__(self):
        return str(self.form_type)

    pass


class FormTemplate(models.Model):
    class Meta:
        verbose_name = 'FormTemplate'
        verbose_name_plural = 'FormTemplates'

    form_type_template_id = models.ForeignKey(FormTypeTemplate, on_delete=models.CASCADE)
    form_title = models.CharField(max_length=200, unique=True, error_messages={
        'unique': 'Form title already exist.', })
    ref_no = models.CharField(max_length=20)
    rev = models.IntegerField(default=1)
    remarks = models.CharField(max_length=200, blank=True)
    is_active = models.BooleanField(default=True)
    creation_time = models.DateTimeField(null=True, blank=True)
    creator_user_id = models.CharField(max_length=50, blank=True)
    last_modification_time = models.DateTimeField(null=True, blank=True)
    last_modifier_user_id = models.CharField(max_length=50, blank=True)
    is_deleted = models.BooleanField(default=False)
    deletion_time = models.DateTimeField(null=True, blank=True)
    delete_user_id = models.CharField(max_length=50, blank=True)

    def __str__(self):
        return str(self.form_title)

    pass


class TemplateDetail(models.Model):
    class Meta:
        verbose_name = 'TemplateDetail'
        verbose_name_plural = 'TemplateDetails'

    group_id = models.ForeignKey(Group, on_delete=models.CASCADE)
    form_template_id = models.ForeignKey(FormTemplate, on_delete=models.CASCADE)
    legend = models.CharField(max_length=5, null=True, blank=True)
    question_line = models.IntegerField(null=True, blank=True)
    question = models.CharField(max_length=500)
    is_boolean_question = models.BooleanField(null=False)
    is_active = models.BooleanField(default=True)
    creation_time = models.DateTimeField(null=True, blank=True)
    creator_user_id = models.CharField(max_length=50, blank=True)
    last_modification_time = models.DateTimeField(null=True, blank=True)
    last_modifier_user_id = models.CharField(max_length=50, blank=True)
    is_deleted = models.BooleanField(default=False)
    deletion_time = models.DateTimeField(null=True, blank=True)
    delete_user_id = models.CharField(max_length=50, blank=True)

    def __str__(self):
        return str(self.question)

    pass


class Inspection01(models.Model):
    class Meta:
        verbose_name = 'Inspection1'
        verbose_name_plural = 'Inspections1'

    form_template_id=models.ForeignKey(FormTemplate, on_delete=models.CASCADE)
    unit_number_id = models.ForeignKey('objects.UnitNumber', on_delete=models.CASCADE)
    inspection_count = models.IntegerField(null=True,default=0)  # for count the reinspection form
    reason = models.CharField(max_length=200, null=True)
    comment = RichTextUploadingField(null=True)
    accept = models.BooleanField(null=True)
    accept_date = models.DateTimeField(default=datetime.now, blank=True, null=True)
    contractor_name = models.CharField(max_length=50, null=True)
    contractor_date = models.DateTimeField(default=datetime.now, blank=True, null=True)
    consultant_name = models.CharField(max_length=50, null=True)
    consultant_date = models.DateTimeField(default=datetime.now, blank=True, null=True)
    remarks = RichTextUploadingField(null=True)
    draw_ref = models.CharField(max_length=15, null=True)
    is_active = models.BooleanField(default=True)
    creation_time = models.DateTimeField(blank=True, null=True)
    creator_user_id = models.CharField(max_length=50, blank=True)
    last_modification_time = models.DateTimeField(null=True, blank=True)
    last_modifier_user_id = models.CharField(max_length=50, blank=True)
    is_deleted = models.BooleanField(default=False)
    deletion_time = models.DateTimeField(null=True, blank=True)
    delete_user_id = models.CharField(max_length=50, blank=True)

    def __str__(self):
        return str(self.id)

    pass


class Inspection02(models.Model):
    class Meta:
        verbose_name = 'Inspection02'
        verbose_name_plural = 'Inspections02'

    inspection01_id = models.ForeignKey(Inspection01, on_delete=models.CASCADE)
    inspection = models.CharField(max_length=25, null=True)
    inspection_count=models.IntegerField(default=1, null=True)
    is_active = models.BooleanField(default=True)
    creation_time = models.DateTimeField(null=True, blank=True)
    creator_user_id = models.CharField(max_length=50, blank=True)
    last_modification_time = models.DateTimeField(null=True, blank=True)
    last_modifier_user_id = models.CharField(max_length=50, blank=True)
    is_deleted = models.BooleanField(default=False)
    deletion_time = models.DateTimeField(null=True, blank=True)
    delete_user_id = models.CharField(max_length=50, blank=True)

    def __str__(self):
        return str(self.id)

    pass

source/QAQC/inspection/forms.py
from django import forms
from .models import *


class ElementForm(forms.ModelForm):
    class Meta:
        widgets = {
            'element': forms.TextInput(
                attrs={'placeholder': 'Eg:Floor'}),
            'description': forms.TextInput(
                attrs={'placeholder': 'Remark / Description (if any)...'}),
        }
        model = Element
        fields = (
            'element',
            'description',
        )


class GroupForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(GroupForm, self).__init__(*args, **kwargs)
        self.fields['defect_group'].label = 'Group'

    class Meta:
        model = Group
        widgets = {
            'element_id': forms.HiddenInput(),
            'defect_group': forms.TextInput(
                attrs={'placeholder': 'Eg:Finishing'}),
            'description': forms.TextInput(
                attrs={'placeholder': 'Remark / Description (if any)...'}),
        }
        fields = (
            'defect_group',
            'description',
            'element_id',
        )


class FormTypeForm(forms.ModelForm):
    class Meta:
        model = FormTypeTemplate
        widgets = {
            'number_series_id': forms.HiddenInput(),
            'form_type': forms.TextInput(
                attrs={'placeholder': 'Eg:Pre Delivery Inspection'}),
            'form_description': forms.TextInput(
                attrs={'placeholder': 'Eg:PDI'}),
        }
        fields = (
            'form_type',
            'form_description',
            'number_series_id',
        )
        labels = {
            'form_type': 'Form Type Name',
            'form_description': 'Form Short Name',
        }


class NumberSeriesForm(forms.ModelForm):
    class Meta:
        model = NumberSeries
        fields = (
            'series',
            'current',
        )


class TemplateForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(TemplateForm, self).__init__(*args, **kwargs)
        self.fields['ref_no'].widget.attrs['readonly'] = True
        self.fields['remarks'].label = 'Remark '
        self.fields['ref_no'].label = 'Ref No'
        self.fields['form_title'].label = 'Form Tittle'

    class Meta:
        model = FormTemplate
        widgets = {
            'form_type_template_id': forms.HiddenInput(),
            'rev': forms.HiddenInput(),
            'form_title': forms.TextInput(
                attrs={'placeholder': 'Eg:FLOOR, WALL, CEILING, DOOR, WINDOW, FIXTURES, M&E'}),
            'remarks': forms.TextInput(
                attrs={'placeholder': 'Form remark(if any)...'}),
        }
        fields = (
            'form_title',
            'ref_no',
            'rev',
            'remarks',
            'form_type_template_id',
        )


class TemplateDetailForm(forms.ModelForm):
    group_id = forms.ModelChoiceField(queryset=Group.objects.filter(is_active=True).order_by('element_id'),
                                      empty_label='Select Group For Questions')

    def __init__(self, *args, **kwargs):
        super(TemplateDetailForm, self).__init__(*args, **kwargs)
        self.fields['question'].label = ''
        self.fields['is_boolean_question'].label = ''
        self.fields['group_id'].label = 'Defect Group'
        self.fields['is_boolean_question'].label = 'Boolean Question(Default = Text)'

    class Meta:
        widgets = {
            'form_template_id': forms.HiddenInput(),
            'legend': forms.HiddenInput(),
            'question_line': forms.HiddenInput(),
            'question': forms.TextInput(
                attrs={'placeholder': 'Enter questions here...(Tick if the answering style is True/False.)'}),

        }
        model = TemplateDetail
        fields = (
            'group_id',
            'form_template_id',
            'legend',
            'question_line',
            'question',
            'is_boolean_question',
        )

source/QAQC/inspection/templates/input/inspection.html
{% extends 'accounts/base.html' %}

{% block content %}
{% load static %}
<div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">{{form.form_template_id.form_title}}

                </h3>
 <div class="dropdown" style="left:35%;" >
    <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown"style="background-color: #707070;">
      View previous inspection
    </button>
    <div class="dropdown-menu" style="color: #000;">
        {% for b in previous_ins %}
      <a class="dropdown-item" href="{% url 'previous_inspection' g=form.id h=forloop.counter %}"style="color: #000;">Rev {{forloop.counter}}</a>
        {% endfor %}
    </div>
  </div>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
              <form role="form" method="Post">
                      {% csrf_token %}
                <div class="card-body">

               <div class="form-group">
                     <div class="form-group">
        {% for a in form.form_template_id.templatedetail_set.all %}
                                        <label>{{a.group_id.element_id.element}}:</label><br>
                                        <label>{{a.group_id.defect_group}}</label><br>
                         &emsp;&emsp;  <label>{{ a.question_line }}.{{a.question}}</label>
                         {% if a.is_boolean_question == True %}
                         &emsp;&emsp;&emsp; <input type="radio" id="radioPrimary1" name="boolean{{ a.question_line }}" value="Yes">Yes
                         &emsp;       <input type="radio" id="radioPrimary2" name="boolean{{ a.question_line }}" value="No">No
                         {% else %}
                         &emsp;       <input type="text" name="boolean{{ a.question_line }}" maxlength="10">
                         {% endif %}
<br> <br><hr>
{% endfor %}

<label>accept</label>
 &emsp;&emsp;<input type="radio" id="radioPrimary1" name="accept" value="True">Yes
           &emsp;<input type="radio" id="radioPrimary2" name="accept" value="False">No
                         <br>
                          <label>reason&emsp;</label>
 <textarea name="reason" cols="40" rows="4"></textarea>
                            <br>
                         <br>
                          <label>comment</label>
 <textarea name="comment" cols="40" rows="4"></textarea>
                     </div>


                    </div>

                </div>
                <!-- /.card-body -->

                <div class="card-footer">
    <button type="button" class="btn btn-default" onclick="goBack()" style="background-color:#dbdbdb;">Back</button>
                  <button type="submit" class="btn btn-primary" name="submit" >Submit</button>
                </div>
              </form>
            </div>
<script>
function goBack() {
  window.history.back();
}
</script>
{% endblock %}

source/QAQC/inspection/templates/input/select_form.html
{% extends 'accounts/base.html' %}

{% block content %}
{% load static %}
	<link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css' %}">
    <link rel="stylesheet" href="{% static 'js/bootstrap3-typeahead.js' %}">
    <link rel="stylesheet" href="{% static 'js/datatables.min.js' %}">
	<link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
<!-- icon css -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
 <script src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
<style>
table.dataTable thead .sorting:after,
table.dataTable thead .sorting:before,
table.dataTable thead .sorting_asc:after,
table.dataTable thead .sorting_asc:before,
table.dataTable thead .sorting_asc_disabled:after,
table.dataTable thead .sorting_asc_disabled:before,
table.dataTable thead .sorting_desc:after,
table.dataTable thead .sorting_desc:before,
table.dataTable thead .sorting_desc_disabled:after,
table.dataTable thead .sorting_desc_disabled:before {
bottom: .5em;
}

</style>
<!-- Select checkbox CSS-->

<!------------------------------ body ----------------------------->
 <br>
    <h1 class="page-header"><span class="fa fa-home" ></span></a>SELECT A FORM TO INSPECT </h1>
  <hr>

<!----------- Table--------------->
  <table class="table table-striped table-bordered" id="company-table" width="100%" >
    <thead>
      <tr>
        <th width="5%" style="text-align:center;" >#
        </th>
        <th width="45%" >Form Title
        </th>
        <th class="th-sm" style="text-align:center;" width="20%">Action
        </th>

      </tr>
    </thead>
    <tbody>


 {% for a in list %}
  <tr>
    <td class="data" width="5%">{{ forloop.counter }}</td>
        <td class="data">{{ a.form_title }}</td>

    <td class="item" style="white-space:nowrap;"width="22%">

          <button type="button" style="display:inline;width:100%;color:black;margin-top:0.5px;" class="btn btn-block btn-warning btn-xs" onclick="window.location.href='{% url 'type_code' a.id %}'">
              <span class="fa fa-eye"></span>Inspection</button>
    </td>


  </tr>
  {% empty %}
        <tr><td colspan="5">Currently no Data Available</td></tr>
    {% endfor %}
    </tbody>
  </table>


<br><br><br><br><br><br><br>


<!------------ End body--------------------- -->
<script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'plugins/datatables/jquery.dataTables.js' %}"></script>
<script src="{% static 'plugins/datatables-bs4/js/dataTables.bootstrap4.js' %}"></script>
<script src="{% static 'dist/js/adminlte.min.js' %}"></script>
<script src="{% static 'dist/js/demo.js' %}"></script>

<script>
$(document).ready(function() {
    $('#company-table').DataTable( {
        "scrollY":        "430px",
        "scrollCollapse": true,
        "paging":         false,
        "info": false,
        "columnDefs": [ {
        "targets": [3],
        "orderable": false} ]
    });
 }
);
</script>
{% endblock %}

source/QAQC/inspection/templates/input/select_form2.html
{% extends 'accounts/base.html' %}

{% block content %}
{% load static %}
	<link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css' %}">
    <link rel="stylesheet" href="{% static 'js/bootstrap3-typeahead.js' %}">
    <link rel="stylesheet" href="{% static 'js/datatables.min.js' %}">
	<link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
<!-- icon css -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
 <script src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
<style>
table.dataTable thead .sorting:after,
table.dataTable thead .sorting:before,
table.dataTable thead .sorting_asc:after,
table.dataTable thead .sorting_asc:before,
table.dataTable thead .sorting_asc_disabled:after,
table.dataTable thead .sorting_asc_disabled:before,
table.dataTable thead .sorting_desc:after,
table.dataTable thead .sorting_desc:before,
table.dataTable thead .sorting_desc_disabled:after,
table.dataTable thead .sorting_desc_disabled:before {
bottom: .5em;
}

</style>
<!-- Select checkbox CSS-->

<!------------------------------ body ----------------------------->
 <br>
    <h1 class="page-header"><span class="fa fa-home" ></span></a>SELECT A FORM TO INSPECT </h1>
  <hr>

<!----------- Table--------------->
  <table class="table table-striped table-bordered" id="company-table" width="100%" >
    <thead>
      <tr>
        <th width="5%" style="text-align:center;" >#
        </th>
        <th width="45%" >Form Title
        </th>
        <th class="th-sm" style="text-align:center;" width="20%">Action
        </th>

      </tr>
    </thead>
    <tbody>


 {% for a in list %}
  <tr>
    <td class="data" width="5%">{{ forloop.counter }}</td>
        <td class="data">{{ a.form_template_id.form_title }}</td>

    <td class="item" style="white-space:nowrap;"width="22%">

          <button type="button" style="display:inline;width:100%;color:black;margin-top:0.5px;" class="btn btn-block btn-warning btn-xs" onclick="window.location.href='{% url 'inspection' a.id %}'">
              <span class="fa fa-eye"></span>Inspection</button>
    </td>


  </tr>
  {% empty %}
        <tr><td colspan="5">Currently no Data Available</td></tr>
    {% endfor %}
    </tbody>
  </table>


<br><br><br><br><br><br><br>


<!------------ End body--------------------- -->
<script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'plugins/datatables/jquery.dataTables.js' %}"></script>
<script src="{% static 'plugins/datatables-bs4/js/dataTables.bootstrap4.js' %}"></script>
<script src="{% static 'dist/js/adminlte.min.js' %}"></script>
<script src="{% static 'dist/js/demo.js' %}"></script>

<script>
$(document).ready(function() {
    $('#company-table').DataTable( {
        "scrollY":        "430px",
        "scrollCollapse": true,
        "paging":         false,
        "info": false,
        "columnDefs": [ {
        "targets": [3],
        "orderable": false} ]
    });
 }
);
</script>
{% endblock %}

source/QAQC/inspection/templates/input/type_inspect_code.html
{% extends 'accounts/base.html' %}

{% block content %}
{% load static %}
<br>
<h1>TYPE YOUR INSPECT CODE</h1>
<br>

<form  method="post" >
        {% csrf_token %}


    <p><label>Inspect code:                  </label> <input type="text" name="inspect_code" maxlength="11"></p>


    <button type="button" class="btn btn-default" onclick="goBack()" style="background-color:#dbdbdb;">Back</button>
    <button type="submit" class="btn btn-primary" >Submit</button><br><br>
</form>
{% if messages %}
{% for message in messages %}
    <div class="alert alert-danger">
    {{ message }}
    </div>
{% endfor %}

{% endif %}
<script>
function goBack() {
  window.history.back();
}
</script>

{% endblock %}

source/QAQC/inspection/templates/input/view_previous_inspection.html
{% extends 'accounts/base.html' %}

{% block content %}
{% load static %}
<div class="card card-primary">
              <div class="card-header">
                  <h3 class="card-title">{{form.form_template_id.form_title}}&emsp;<strong>Rev {{h}}</strong>

                </h3>

                   <div class="dropdown" style="left:35%;" >
    <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown"style="background-color: #707070;">
      View previous inspection
    </button>
    <div class="dropdown-menu" style="color: #000; ">
        <a class="dropdown-item" href="{% url 'inspection' form.id  %}"style="color: #000;">Back to Input</a>
        {% for b in previous_ins %}
      <a class="dropdown-item" href="{% url 'previous_inspection' g=form.id h=forloop.counter %}"style="color: #000;">Rev {{forloop.counter}}</a>
        {% endfor %}
    </div>
  </div>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
              <form role="form" method="Post">
                      {% csrf_token %}
                <div class="card-body">

               <div class="form-group">
                     <div class="form-group">
                         <div style="float: left;width: 900px;">
                           {% for a in form.form_template_id.templatedetail_set.all %}
                          <label>{{a.group_id.element_id.element}}:</label><br>
                                        <label>{{a.group_id.defect_group}}</label><br>
                         &emsp;&emsp;  <label>{{ a.question_line }}.{{a.question}}</label>   <br><br><hr>
                         {% endfor %}
                         </div>


                         <div style="float: left; align:center;">Inspection on Rev {{h}}
                              <br><br>
                           {% for j in input %}
                        <label>{{j.inspection}}</label><br><br><br> <br><br>
                         {% endfor %}
                         </div>


                     </div>


                    </div>

                </div>
                <!-- /.card-body -->

                <div class="card-footer">
    <button type="button" class="btn btn-default" onclick="goBack()" style="background-color:#dbdbdb;">Back</button>
                </div>
              </form>
            </div>
<script>
function goBack() {
  window.history.back();
}
</script>
{% endblock %}